import Head from 'next/head';
import { DotGothic16, Inter, Silkscreen } from '@next/font/google';
import PointerTraceCircle from '@/components/views/PointerTraceCircle';
import TitleSection from '@/components/views/TitleSection';
import AboutSection from '@/components/views/AboutSection';
import LoadingScreenContainer from '@/components/containers/LoadingScreenContainer';
import WorksSection from '@/components/views/WorksSection';
import LastSection from '@/components/views/LastSection';

const inter = Inter({ subsets: ['latin'] });

const silkscreen_regular = Silkscreen({
  weight: '400',
  subsets: ['latin'],
});
const silkscreen_bold = Silkscreen({
  weight: '700',
  subsets: ['latin'],
});
const dotgothic16_regular = DotGothic16({
  weight: '400',
  subsets: ['latin-ext'],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative bg-dark-gray-1 text-white grid gap-10 flex flex-col gap-[100vh] z-0">
        <PointerTraceCircle />
        <TitleSection />
        <AboutSection />
        <WorksSection />
        <LastSection />
      </main>
      <LoadingScreenContainer />
    </>
  );
}
